name: Example AKS Deployment

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src/**'
      - 'infrastructure/**'
      - '.github/workflows/example-aks-deploy.yaml'
  pull_request:
    branches: [ 'main' ]
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/aks-deploy-dotnet.yaml
    with:
      environment: preview
      resource_group_name: rg-myapp-preview-usw2
      stack_name: stack-myapp-preview
      template_file: infrastructure/main.bicep
      params_file: infrastructure/main.preview.bicepparam
      infra_path_prefix: infrastructure/
      force_infra: false
      # JSON array of applications to build and deploy
      applications_json: |
        [
          {
            "path": "src/api",
            "name": "myapp-api",
            "image": "myapp/api",
            "dockerfile": "Dockerfile"
          },
          {
            "path": "src/worker",
            "name": "myapp-worker",
            "image": "myapp/worker",
            "dockerfile": "Dockerfile"
          }
        ]
      dotnet_version: '8.0'
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      acr_name: ${{ vars.ACR_NAME }}
      # ArgoCD configuration - update this URL to your ArgoCD cluster or manifests repo
      argocd_cluster_url: https://github.com/yourorg/k8s-manifests/blob/main/clusters/preview/apps
      argocd_toolchain: helmfile
      argocd_namespace: preview
      argocd_synchronously: true
      argocd_debug: false
    secrets:
      GITHUB_AUTH_PAT: ${{ secrets.GITHUB_AUTH_PAT }}

  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/aks-deploy-dotnet.yaml
    with:
      environment: prd
      resource_group_name: rg-myapp-prd-usw2
      stack_name: stack-myapp-prd
      template_file: infrastructure/main.bicep
      params_file: infrastructure/main.prd.bicepparam
      infra_path_prefix: infrastructure/
      force_infra: false
      applications_json: |
        [
          {
            "path": "src/api",
            "name": "myapp-api-prd",
            "image": "myapp/api",
            "dockerfile": "Dockerfile"
          },
          {
            "path": "src/worker",
            "name": "myapp-worker-prd",
            "image": "myapp/worker",
            "dockerfile": "Dockerfile"
          }
        ]
      dotnet_version: '8.0'
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      acr_name: ${{ vars.ACR_NAME }}
      argocd_cluster_url: https://github.com/yourorg/k8s-manifests/blob/main/clusters/production/apps
      argocd_toolchain: helmfile
      argocd_namespace: production
      argocd_synchronously: true
      argocd_debug: false
    secrets:
      GITHUB_AUTH_PAT: ${{ secrets.GITHUB_AUTH_PAT }}
